export const properties = [
  {
    id: '1',
    name: 'Офіс в центрі',
    description: 'Сучасний офіс з видом на центр міста',
    price: 15000,
    location: 'Київ, вул. Хрещатик 1',
    geometry: {
      type: 'Point',
      coordinates: [30.5234, 50.4501],
    },
  },
  {
    id: '2',
    name: 'Комерційне приміщення',
    description: 'Приміщення під магазин у прохідному місці',
    price: 8000,
    location: 'Київ, вул. Лісова 15',
    geometry: {
      type: 'Point',
      coordinates: [30.5111, 50.4554],
    },
  },
  {
    id: '3',
    name: 'Офіс біля метро',
    description: 'Офіс біля зручної транспортної розв’язки',
    price: 10000,
    location: 'Київ, вул. Голосіївська 10',
    geometry: {
      type: 'Point',
      coordinates: [30.5081, 50.401],
    },
  },
  {
    id: '4',
    name: 'Бізнес-центр',
    description: 'Приміщення у бізнес-центрі класу A',
    price: 20000,
    location: 'Київ, просп. Перемоги 5',
    geometry: {
      type: 'Point',
      coordinates: [30.488, 50.4505],
    },
  },
  {
    id: '5',
    name: 'Смарт-квартира в новобудові',
    description: 'Компактне житло з сучасним ремонтом',
    price: 9500,
    location: 'Київ, вул. Драгоманова 12',
    geometry: {
      type: 'Point',
      coordinates: [30.6421, 50.3965],
    },
  },
  {
    id: '6',
    name: 'Офіс з паркінгом',
    description: 'Зручне розташування + паркінг',
    price: 14000,
    location: 'Київ, вул. Жилянська 99',
    geometry: {
      type: 'Point',
      coordinates: [30.4982, 50.4389],
    },
  },
  {
    id: '7',
    name: 'Квартира біля парку',
    description: 'Затишна 2-кімнатна квартира з видом на парк',
    price: 11000,
    location: 'Київ, вул. Січових Стрільців 25',
    geometry: {
      type: 'Point',
      coordinates: [30.5056, 50.4544],
    },
  },
  {
    id: '9',
    name: 'Квартира на лівому березі',
    description: 'Простора квартира біля станції метро Лівобережна',
    price: 10000,
    location: 'Київ, вул. Раїси Окіпної 7',
    geometry: {
      type: 'Point',
      coordinates: [30.5988, 50.4492],
    },
  },
  {
    id: '10',
    name: 'Квартира в центрі',
    description: 'Трикімнатна квартира з високими стелями',
    price: 17000,
    location: 'Київ, вул. Володимирська 45',
    geometry: {
      type: 'Point',
      coordinates: [30.5164, 50.4453],
    },
  },
  {
    id: '11',
    name: 'Квартира з ремонтом',
    description: 'Квартира після капітального ремонту, повністю мебльована',
    price: 12500,
    location: 'Київ, просп. Лобановського 33',
    geometry: {
      type: 'Point',
      coordinates: [30.4799, 50.4087],
    },
  },
  {
    id: '12',
    name: 'Житло біля метро Академмістечко',
    description: 'Квартира з двома балконами, поруч ліс',
    price: 9000,
    location: 'Київ, вул. Академіка Вернадського 87',
    geometry: {
      type: 'Point',
      coordinates: [30.3554, 50.4642],
    },
  },
  {
    id: '13',
    name: 'Пентхаус з терасою',
    description: 'Елітне житло з панорамним видом на місто',
    price: 30000,
    location: 'Київ, вул. Кловський узвіз 7',
    geometry: {
      type: 'Point',
      coordinates: [30.5287, 50.4391],
    },
  },
  {
    id: '14',
    name: 'Квартира у тихому дворі',
    description: 'Тихий район з хорошою інфраструктурою',
    price: 10500,
    location: 'Київ, вул. Борщагівська 182',
    geometry: {
      type: 'Point',
      coordinates: [30.4012, 50.4308],
    },
  },
  {
    id: '15',
    name: 'Однокімнатна на Троєщині',
    description: 'Доступна квартира для молодої пари',
    price: 8000,
    location: 'Київ, вул. Милославська 24',
    geometry: {
      type: 'Point',
      coordinates: [30.6315, 50.5167],
    },
  },
  {
    id: '16',
    name: 'Квартира з панорамними вікнами',
    description: 'Світла та простора, поруч ТРЦ',
    price: 13500,
    location: 'Київ, вул. Антоновича 131',
    geometry: {
      type: 'Point',
      coordinates: [30.5101, 50.4255],
    },
  },
]
